# Generated by Django 4.1.6 on 2023-04-05 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcategory",
            options={
                "verbose_name": "Kategorie příspěvku",
                "verbose_name_plural": "Kategorie příspěvků",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="product_category",
            new_name="post_category",
        ),
    ]
