from .category_tree_view import *
from .category_detail_view import *
from .product_detail_view import *
from .index_view import *
from .message_form_view import *
from .user_form_view import *
from .profile_form_view import *
from .place_order_view import *
from .cart_view import *