# Generated by Django 4.1.6 on 2023-02-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_deliveryinformation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryinformation",
            name="alias",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
