# Generated by Django 4.1.6 on 2023-03-10 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customuser_profile_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryinformation",
            old_name="phone",
            new_name="delivery_phone",
        ),
    ]
