# Generated by Django 4.1.6 on 2023-03-10 19:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_phone_deliveryinformation_delivery_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                unique=True,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="delivery_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
