# Generated by Django 4.1.6 on 2023-03-10 19:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_customuser_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryinformation",
            name="delivery_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="phone number"
            ),
        ),
    ]
