# Generated by Django 4.1.6 on 2023-03-14 15:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_deliveryinformation_delivery_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryinformation",
            name="delivery_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
    ]
