# Generated by Django 4.1.6 on 2023-03-28 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_deliveryinformation_delivery_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryinformation",
            options={
                "verbose_name": "Dodací údaj",
                "verbose_name_plural": "Dodací údaje",
            },
        ),
        migrations.CreateModel(
            name="BillingInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "address_line1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("vat_id", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_informations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fakturační údaj",
                "verbose_name_plural": "Fakturační údaje",
            },
        ),
    ]
