# Generated by Django 4.1.6 on 2023-03-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_deliveryinformation_options_billinginformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryinformation",
            name="address_line1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="address_line2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="postal_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
