# Generated by Django 4.1.6 on 2023-04-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_deliveryinformation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_billing_method",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.deliveryinformation",
                verbose_name="Delivery information",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="alias",
            field=models.CharField(
                blank=True, default="Secret", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="alias",
            field=models.CharField(
                blank=True, default="Secret", max_length=50, null=True
            ),
        ),
    ]
