# Generated by Django 4.1.6 on 2023-04-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_customuser_preferred_billing_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_delivery_information",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"user": models.F("pk")},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_information",
                to="users.deliveryinformation",
                verbose_name="Preferred delivery information",
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryinformation",
            name="alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
