# Generated by Django 4.1.6 on 2023-04-01 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_customuser_preferred_delivery_information_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="preferred_billing_method",
            new_name="preferred_billing_information",
        ),
    ]
