# Generated by Django 4.1.6 on 2023-04-01 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0017_rename_preferred_billing_method_customuser_preferred_billing_information",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_billing_information",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={
                    "pk": django.db.models.expressions.OuterRef("user_id")
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferred_by_user",
                to="users.billinginformation",
                verbose_name="Preferred billing information",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="preferred_delivery_information",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={
                    "pk": django.db.models.expressions.OuterRef("user_id")
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_information_set",
                to="users.deliveryinformation",
                verbose_name="Preferred delivery information",
            ),
        ),
    ]
