# Generated by Django 4.1.6 on 2023-04-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_customuser_preferred_billing_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryinformation",
            name="delivery_phone",
            field=models.CharField(max_length=15, verbose_name="phone number"),
        ),
    ]
