# Generated by Django 4.1.6 on 2023-04-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_deliveryinformation_delivery_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="phone number"),
        ),
    ]
