# Generated by Django 4.1.6 on 2023-04-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_billing_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_billing_informationby_user",
                to="users.billinginformation",
                verbose_name="Preferred billing information",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="preferred_delivery_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_delivery_information_by_user",
                to="users.deliveryinformation",
                verbose_name="Preferred delivery information",
            ),
        ),
    ]
