# Generated by Django 4.1.6 on 2023-03-04 13:14

from django.db import migrations, models
import settings.models.settings


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=12)),
                ("mobile_phone", models.CharField(blank=True, max_length=12)),
                ("address_line1", models.CharField(blank=True, max_length=500)),
                ("address_line2", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
            bases=(settings.models.settings.MaxNumInstancesMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GeneralInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_info", models.CharField(max_length=50)),
                (
                    "footer_copyright",
                    models.CharField(default="&copy;", max_length=250),
                ),
                ("github_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "GeneralInfo",
                "verbose_name_plural": "GeneralInfos",
            },
            bases=(settings.models.settings.MaxNumInstancesMixin, models.Model),
        ),
    ]
