# Generated by Django 4.1.6 on 2023-03-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address_line1",
            field=models.CharField(blank=True, default="Nová ulice 6", max_length=500),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, default="Praha", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(blank=True, default="Česko", max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="email@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile_phone",
            field=models.CharField(
                blank=True, default="+420 123 456 789", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, default="+420 123 456 789", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(blank=True, default="CZ-123 456", max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="seller_name",
            field=models.CharField(default="Název prodejce", max_length=50),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="company_info",
            field=models.TextField(default="Nějaké info o společnosti", max_length=50),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="company_name",
            field=models.CharField(default="Název společnosti", max_length=50),
        ),
    ]
