# Generated by Django 4.1.6 on 2023-03-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_alter_contact_address_line1_alter_contact_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="google_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile_phone",
            field=models.CharField(
                blank=True, default="+420 123 456 789", max_length=20
            ),
        ),
    ]
