# Generated by Django 4.1.6 on 2023-03-06 22:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_generalinfo_facebook_url_generalinfo_google_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinfo",
            name="company_info",
            field=ckeditor.fields.RichTextField(
                default="Nějaké info o společnosti", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="footer_copyright",
            field=ckeditor.fields.RichTextField(default="&copy;", max_length=250),
        ),
    ]
