# Generated by Django 4.1.6 on 2023-03-28 19:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_alter_generalinfo_company_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinfo",
            name="company_info",
            field=ckeditor.fields.RichTextField(
                default="Nějaké info o společnosti", max_length=500
            ),
        ),
    ]
