# Generated by Django 4.1.6 on 2023-04-09 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0007_alter_articles_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Articles",
        ),
    ]
