# Generated by Django 4.1.6 on 2023-04-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0008_delete_articles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="seller_name",
        ),
        migrations.AddField(
            model_name="contact",
            name="alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address_line1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address_line2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
