# Generated by Django 4.1.6 on 2023-04-14 01:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0009_remove_contact_seller_name_contact_alias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="about_us",
            field=ckeditor.fields.RichTextField(default="O nás", max_length=1000),
        ),
    ]
