# Generated by Django 4.1.6 on 2023-04-22 03:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0010_generalinfo_about_us"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinfo",
            name="about_us",
            field=ckeditor.fields.RichTextField(default="O nás"),
        ),
    ]
