# Generated by Django 4.1.6 on 2023-04-25 10:54

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0021_alter_customuser_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SAVED", "Saved"),
                            ("PLACED", "Placed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Košík",
                "verbose_name_plural": "Košíky",
            },
        ),
        migrations.CreateModel(
            name="CartDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(default="", max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("posted_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name": "Kontaktní formulář",
                "verbose_name_plural": "Kontaktní formuláře",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("product_sku", models.CharField(max_length=50, unique=True)),
                ("product_description", ckeditor.fields.RichTextField()),
                ("product_evaluation", models.FloatField(default=0)),
                (
                    "product_short_description",
                    ckeditor.fields.RichTextField(max_length=200),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("category_name", models.CharField(max_length=50)),
                ("category_description", ckeditor.fields.RichTextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategorie produktu",
                "verbose_name_plural": "Kategorie produktů",
            },
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory_name", models.CharField(max_length=50)),
                ("inventory_description", models.TextField()),
                ("quantity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name": "Sklad produktu",
                "verbose_name_plural": "Sklad produktů",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_title", models.CharField(max_length=30, verbose_name="Příznaky")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("bg_color", models.CharField(max_length=7)),
                ("font_color", models.CharField(max_length=7)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Příznak",
                "verbose_name_plural": "Příznaky",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variants",
                        to="eshop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varianta produktu",
                "verbose_name_plural": "Varianty produktu",
            },
        ),
        migrations.CreateModel(
            name="ProductPriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="CZK", max_length=3)),
                ("price_list_name", models.CharField(max_length=50)),
                ("price_list_description", models.TextField()),
                ("price", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "product",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eshop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ceník produktu",
                "verbose_name_plural": "Ceníky produktů",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="eshop/uploads/products"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="eshop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produktový obrázek",
                "verbose_name_plural": "Produktové obrázky",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="eshop.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_tags",
            field=models.ManyToManyField(blank=True, to="eshop.tag"),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLACED", "Placed"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_info",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.billinginformation",
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eshop.cart",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_info",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.deliveryinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objednávka",
                "verbose_name_plural": "Objednávky",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="eshop.cart",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="eshop.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="eshop.deliverymethod",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="eshop.paymentmethod",
            ),
        ),
    ]
