# Generated by Django 4.1.6 on 2023-04-26 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0002_alter_product_product_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="code",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eshop.cartdiscount",
            ),
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("amount", "Amount")],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="end_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="start_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="eshop.deliverymethod",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="eshop.paymentmethod",
            ),
        ),
    ]
