# Generated by Django 4.1.6 on 2023-03-01 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0003_remove_product_product_image_productvariant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="created_at",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
