# Generated by Django 4.1.6 on 2023-02-21 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_deliveryinformation_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryinformation',
            options={'verbose_name': 'Adresa', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
