# Generated by Django 4.1.6 on 2023-04-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0003_cart_code_cartdiscount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdiscount",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cartdiscount",
            name="start_date",
            field=models.DateField(),
        ),
    ]
