# Generated by Django 4.1.6 on 2023-04-26 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0004_alter_cartdiscount_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdiscount",
            name="single_use",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cartdiscount",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
