# Generated by Django 4.1.6 on 2023-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_deliveryinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinformation',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
