# Generated by Django 4.1.6 on 2023-04-26 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0005_cartdiscount_single_use_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartdiscount",
            old_name="single_use",
            new_name="is_single_use",
        ),
    ]
