# Generated by Django 4.1.6 on 2023-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0005_contact_generalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="footer_copyright",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
