# Generated by Django 4.1.6 on 2023-04-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0006_rename_single_use_cartdiscount_is_single_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdiscount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="code",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eshop.cartdiscount",
            ),
        ),
    ]
