# Generated by Django 4.1.6 on 2023-03-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0006_generalinfo_footer_copyright"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="footer_copyright",
            field=models.CharField(default="&copy;", max_length=250),
        ),
    ]
