# Generated by Django 4.1.6 on 2023-03-06 22:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0009_alter_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
