# Generated by Django 4.1.6 on 2023-03-10 17:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0012_rename_size_productvariant_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="category_description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
