# Generated by Django 4.1.6 on 2023-03-11 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0013_alter_productcategory_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_short_description",
            field=ckeditor.fields.RichTextField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
