# Generated by Django 4.1.6 on 2023-03-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0018_cart_alter_order_status_alter_order_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="eshop.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
