# Generated by Django 4.1.6 on 2023-03-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0019_alter_cartitem_product_variant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_code", models.CharField(max_length=50, unique=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="eshop.cart",
                    ),
                ),
            ],
        ),
    ]
