# Generated by Django 4.1.6 on 2023-03-25 17:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0020_cartdiscount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name="cartdiscount",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartdiscount",
            name="discount_code",
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="code",
            field=models.CharField(default="", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartdiscount",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
