# Generated by Django 4.1.6 on 2023-03-25 17:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0021_deliverymethod_paymentmethod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdiscount",
            name="code",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
