# Generated by Django 4.1.6 on 2023-03-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0023_cart_delivery_method_cart_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="delivery_method",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="eshop.deliverymethod",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="eshop.paymentmethod",
            ),
        ),
    ]
