# Generated by Django 4.1.6 on 2023-03-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0024_alter_cart_delivery_method_alter_cart_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_variant",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
