# Generated by Django 4.1.6 on 2023-03-28 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eshop", "0026_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_info",
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
