# Generated by Django 4.1.6 on 2023-03-28 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_deliveryinformation_address_line1_and_more"),
        ("eshop", "0027_remove_order_delivery_info_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_info",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.deliveryinformation",
            ),
            preserve_default=False,
        ),
    ]
