# Generated by Django 4.1.6 on 2023-03-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_deliveryinformation_user"),
        ("eshop", "0028_order_delivery_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="eshop.deliverymethod",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="eshop.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.billinginformation",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.deliveryinformation",
            ),
        ),
    ]
