# Generated by Django 4.1.6 on 2023-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0032_alter_order_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Saved"), (2, "Placed")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
