# Generated by Django 4.1.6 on 2023-04-01 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0033_cart_status_alter_order_note_delete_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
    ]
