# Generated by Django 4.1.6 on 2023-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0034_remove_cart_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
