# Generated by Django 4.1.6 on 2023-04-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0036_order_status_alter_cart_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SAVED", "Saved"), ("PLACED", "Placed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PLACED", "Placed"),
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
