# Generated by Django 4.1.6 on 2023-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0037_alter_cart_status_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="original_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_inventory",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_price",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
