# Generated by Django 4.1.6 on 2023-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0039_rename_product_tag_product_product_tags_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="color",
            new_name="bg_color",
        ),
        migrations.AddField(
            model_name="tag",
            name="font_color",
            field=models.CharField(default="", max_length=7),
            preserve_default=False,
        ),
    ]
