# Generated by Django 4.1.6 on 2023-04-12 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0040_rename_color_tag_bg_color_tag_font_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="a", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
