# Generated by Django 4.1.6 on 2023-04-12 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0041_tag_description_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
